# Generated by Django 4.2.7 on 2024-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_permission_name_delete_googleaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailaccounts',
            name='google_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('ONLY_IMG', 'Image as Content'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_IMG', 'HTML to Image'), ('HTML', 'HTML'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('PDF', 'PDF'), ('IMG_TO_PDF', 'Image to PDF')], max_length=255),
        ),
    ]
