# Generated by Django 4.2.7 on 2024-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_emailaccounts_expiry_time_emailaccounts_google_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.FileField(upload_to='credentials/')),
            ],
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('PDF', 'PDF'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('IMG_TO_PDF', 'Image to PDF'), ('HTML', 'HTML'), ('HTML_IMG', 'HTML to Image'), ('ONLY_IMG', 'Image as Content')], max_length=255),
        ),
    ]
