# Generated by Django 4.2.7 on 2024-12-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_credentials_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='credentials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML_TO_PDF', 'HTML to PDF'), ('PDF', 'PDF'), ('HTML', 'HTML'), ('HTML_TO_IMG', 'HTML to Image'), ('IMG_TO_PDF', 'Image to PDF'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('ONLY_IMG', 'Image as Content')], max_length=255),
        ),
    ]
