# Generated by Django 4.2.7 on 2024-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_emailaccounts_credentials_alter_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sending_from',
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('ONLY_IMG', 'Image as Content'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('PDF', 'PDF'), ('HTML', 'HTML')], max_length=255),
        ),
    ]
