# Generated by Django 4.2.7 on 2024-12-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_campaign_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender_name',
            field=models.CharField(default='{randomName}', max_length=150),
        ),
        migrations.AddField(
            model_name='messages',
            name='unsuscribe_url',
            field=models.CharField(default='mailto:{receiverEmail}', max_length=150),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_IMG', 'HTML to Image'), ('PDF', 'PDF'), ('ONLY_IMG', 'Image as Content'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML', 'HTML')], max_length=255),
        ),
    ]
