# Generated by Django 4.2.7 on 2024-12-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_audiencedata_tag_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audience_data',
            field=models.CharField(default='Target', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_from',
            field=models.CharField(choices=[('API', 'API'), ('SMTP', 'SMTP')], default='API', max_length=10),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('PDF', 'PDF'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('IMG_TO_PDF', 'Image to PDF'), ('ONLY_IMG', 'Image as Content'), ('HTML', 'HTML')], max_length=255),
        ),
    ]
