# Generated by Django 4.2.7 on 2024-12-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_campaign_status_alter_permission_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text="SMTP host, e.g., 'smtp.example.com'", max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP port, e.g., 587 for TLS or 465 for SSL')),
                ('secure', models.BooleanField(choices=[(False, 'Non-SSL/TLS (Default Port 587)'), (True, 'SSL/TLS (Port 465)')], default=False, help_text='True for SSL/TLS (Port 465), False for non-SSL/TLS (Port 587)')),
                ('auth_user', models.EmailField(help_text='Email address used for SMTP authentication', max_length=254)),
                ('auth_password', models.CharField(help_text='Password for the SMTP authentication email', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML', 'HTML'), ('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_PDF', 'HTML to PDF'), ('ONLY_IMG', 'Image as Content'), ('PDF', 'PDF')], max_length=255),
        ),
    ]
