# Generated by Django 4.2.7 on 2024-12-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_smtpconfiguration_user_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='format_type',
            field=models.CharField(choices=[('HTML', 'HTML Message Only'), ('HTML_IMG', 'HTML with Image Attachment'), ('ONLY_IMG', 'Image as Content'), ('HTML_TO_IMG', 'HTML to Image Conversion'), ('HTML_IMG_INLINE', 'HTML to Image Inline'), ('PDF', 'PDF Attachment'), ('IMG_TO_PDF', 'Image to PDF Conversion'), ('HTML_TO_PDF', 'HTML to PDF Conversion'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF')], default='HTML', max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML', 'HTML'), ('PDF', 'PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('ONLY_IMG', 'Image as Content'), ('HTML_IMG', 'HTML with Image Attachment'), ('IMG_TO_PDF', 'Image to PDF'), ('HTML_IMG_INLINE', 'HTML to Image Inline'), ('HTML_TO_PDF', 'HTML to PDF')], max_length=255),
        ),
    ]
